# Generated by Django 5.0.2 on 2024-02-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
