# Generated by Django 5.0.2 on 2024-02-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', max_length=50, verbose_name='카테고리 이름'),
        ),
        migrations.AddField(
            model_name='menu',
            name='category_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default='', max_length=50, verbose_name='메뉴 이름'),
        ),
        migrations.AddField(
            model_name='menu',
            name='time',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_tool',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='recipe_process',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='recipe_process',
            name='process',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe_process',
            name='recipe_id',
            field=models.IntegerField(default=''),
        ),
    ]
