# Generated by Django 5.0.2 on 2024-02-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_category_category_name_menu_category_id_menu_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category_id',
            field=models.IntegerField(),
        ),
    ]
